### ISSUE TITLE
Critical (?) Error when console uses /invfix

### ISSUE THREAD

**Issue by SalmonGER** [GMNetwork/InventoryFix#1]
Solution:
Check if $sender is console and send a "nope :P" message

**Comment by Aericio** [comment]
The likeliness of console using that command is a low chance.

**Comment by SalmonGER** [comment]
Then this is low priority

**Comment by SalmonGER** [comment]
@Aericio And now it's 0% xD

**Comment by SalmonGER** [comment]
> The likeliness of console using that command is a low chance.

And now it's **0%** xD
